[env:esp32dev]
platform = espressif32
board = esp32doit-devkit1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; LittleFS 設置
board_build.filesystem = littlefs
board_build.partitions = default.csv

; OTA 更新設置
upload_protocol = espota
upload_port = 192.168.4.1
upload_flags = 
    --auth=
    --port=3232

; 库依赖（如需要，可添加其他库）
lib_deps = 
